
package org.virtualbox;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-16T12:59:38.558+02:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "RuntimeFault", targetNamespace = "http://www.virtualbox.org/")
public class RuntimeFaultMsg extends Exception {
    
    private org.virtualbox.RuntimeFault runtimeFault;

    public RuntimeFaultMsg() {
        super();
    }
    
    public RuntimeFaultMsg(String message) {
        super(message);
    }
    
    public RuntimeFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RuntimeFaultMsg(String message, org.virtualbox.RuntimeFault runtimeFault) {
        super(message);
        this.runtimeFault = runtimeFault;
    }

    public RuntimeFaultMsg(String message, org.virtualbox.RuntimeFault runtimeFault, Throwable cause) {
        super(message, cause);
        this.runtimeFault = runtimeFault;
    }

    public org.virtualbox.RuntimeFault getFaultInfo() {
        return this.runtimeFault;
    }
}
