package org.virtualbox.service;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.virtualbox.VboxPortType;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-16T12:59:33.175+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "vboxService", 
                  wsdlLocation = "wsdl/vboxwebService.wsdl",
                  targetNamespace = "http://www.virtualbox.org/Service") 
public class VboxService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.virtualbox.org/Service", "vboxService");
    public final static QName VboxServicePort = new QName("http://www.virtualbox.org/Service", "vboxServicePort");
    static {
        URL url = VboxService.class.getResource("wsdl/vboxwebService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(VboxService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/vboxwebService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public VboxService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VboxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VboxService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns VboxPortType
     */
    @WebEndpoint(name = "vboxServicePort")
    public VboxPortType getVboxServicePort() {
        return super.getPort(VboxServicePort, VboxPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VboxPortType
     */
    @WebEndpoint(name = "vboxServicePort")
    public VboxPortType getVboxServicePort(WebServiceFeature... features) {
        return super.getPort(VboxServicePort, VboxPortType.class, features);
    }

}
